// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-cq37OsnAkk4jautCXa2JqZVEKL0YOI',
    appId: '1:581630773747:web:2b10e919ebab22a4e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    authDomain: 'besheger-services.firebaseapp.com',
    storageBucket: 'besheger-services.appspot.com',
    measurementId: 'G-J69HS6VFYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2lSTPCEf4FSEQvUTh2DcTrcwNy7qHa7k',
    appId: '1:581630773747:android:72691cba0b50f705e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqI53M5ubFu01tSHKvyj-UGMJjiMSZ31M',
    appId: '1:581630773747:ios:d0a03d85b8da6a78e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
    iosBundleId: 'com.besheger.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqI53M5ubFu01tSHKvyj-UGMJjiMSZ31M',
    appId: '1:581630773747:ios:d0a03d85b8da6a78e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
    iosBundleId: 'com.besheger.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-cq37OsnAkk4jautCXa2JqZVEKL0YOI',
    appId: '1:581630773747:web:a7e843f2d6fae8e1e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    authDomain: 'besheger-services.firebaseapp.com',
    storageBucket: 'besheger-services.appspot.com',
    measurementId: 'G-QNYLWMRG15',
  );

}